# Site settings
course_name: High-performance and Distributed Computing
course_description: "The course on High-Performance and Distributed Computing for Big Data sets the basics for understanding and using advanced computing infraestructures to solve biomedical problems that use large amounts of data. This course is coordinated by Universitat Autònoma de Barcelona (UAB), in collaboration with Universitat de Lleida (UdL). The part coordinated by UdL explores the fundamental concepts, architectures, and applications of Cloud Computing and Big Data, with a focus on their implementation in real-world scenarios, particularly in the health domain. Students will gain hands-on experience with Amazon Web Services (AWS)."
course_semester: "Spring 2024"

baseurl: "/sp2024"
url: "http://HPDC-UDL.github.io/"

schoolname: "Escola Politècnica Superior (Universitat de Lleida)"
schoolurl: "https://udl.cat"

github_username: JordiMateoUdL 
google_scholar_id: t-vbHCoAAAAJ 
orcid_id: 0000-0002-1660-0380 
twitter_username: MatForJordi 

address: |
    Escola Politècnica Superior (Universitat de Lleida)
    Campus Universitari Igualada-UdL / Pla de la Massa
    Av. Pla de la Massa, 8 - Igualada

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: false
    lectures:
        output: true
    assignments:
        output: false
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
